package com.example.recycleapp

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.RecyclerView

class MainActivity : AppCompatActivity() {
    private lateinit var recyclerView: RecyclerView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        recyclerView = findViewById(R.id.main_recycler_view)

        val listOfMovies = getListOfMovies()
        val fruitsAdapter = FruitsAdapter(listOfMovies)
        recyclerView.adapter = fruitsAdapter
    }


    private fun getListOfMovies(): List<Fruit>{
        val movies = mutableListOf<Fruit>()
        movies.add(Fruit("Apple", R.drawable.apple,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Avocado",R.drawable.avocado,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Banana",R.drawable.banana,"The benefits of bananas go beyond their potassium content. Along \nwith providing 7% of the Daily Value (DV) for potassium, bananas contain:\n Vitamin B6: 27% of the DV\n Vitamin C: 12% of the DV\nMagnesium: 8% of the DV\n In addition, they offer a wide variety of plant compounds called polyphenols and phytosterols,\n both of which support your overall health. Furthermore, they’re high in prebiotics, a type of fiber that promotes \nthe growth of beneficial bacteria in the gut.\nNote that green, unripe bananas are higher in resistant starch than ripe ones, and they’re a good source of the dietary \nfiber pectin. Both of these have been linked to a number of health benefits, including improved blood sugar \ncontrol and better digestive health.\nMeanwhile, ripe bananas are an excellent source of easily digested carbs, \nmaking them great to fuel up on before a workout."))
        movies.add(Fruit("Grape",R.drawable.grape,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Grape Fruit",R.drawable.grapefruit,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Kiwi",R.drawable.kiwi,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Lemon", R.drawable.lemon,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Orange",R.drawable.orange,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Peach",R.drawable.peach,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Pineapple", R.drawable.pineapple,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Plums",R.drawable.plums,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        movies.add(Fruit("Watermelon",R.drawable.watermelon,"One of the most popular fruits, apples are chock-full of nutrition.\nThey’re rich in both soluble and insoluble fiber, such as pectin, hemicellulose, and cellulose. \nThese help you manage your blood sugar levels, promote good digestion, and support gut and heart health.\n In addition, they’re a good source of vitamin C and plant polyphenols, \nwhich are disease-fighting compounds found in plants. In fact, consuming apples regularly may lower your \nrisk of heart disease, stroke, cancer, overweight, obesity, and neurological disorders.\nNote that most of the polyphenols in apples are located just below the skin, so be sure to eat \nit to reap the greatest benefits."))
        return movies
    }
}